[project]
authors = ["Matt Koski <maccam912@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "camera-bot-drive"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
certs = "openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj \"/C=US/ST=State/L=City/O=Organization/CN=localhost\""
serve-https = "uvicorn server:app --host 0.0.0.0 --port 8000 --ssl-keyfile=key.pem --ssl-certfile=cert.pem"
serve = { depends-on = ["certs", "serve-https"] }

[dependencies]
python = ">=3.12.5,<4"
litestar = ">=2.11.0,<3"
uvicorn = ">=0.30.6,<0.31"
openssl = ">=3.3.2,<4"
